### PR TITLE
Add password components for Vue 2 and Vue 3

### PR DESCRIPTION
**Pull request by meduzen-immoweb**
The Vue 2 component is in [`packages/vue-2-password`](https://github.com/axel-springer-kugawana/iwb_serenity/tree/b6166032cf8417a47967627ac19847d9724cc753/packages/vue-2-password).
The Vue 3+ component is in [`packages/vue-password`](https://github.com/axel-springer-kugawana/iwb_serenity/tree/b6166032cf8417a47967627ac19847d9724cc753/packages/vue-password).

None of them are currently published. But we can surely publish a 1.0.0-rc.1 to test them.

## The component

It is the same as in [this PR](https://github.com/axel-springer-kugawana/iw_encoding_funnel/pull/333), with the following changes:
- it accepts a [`in-modal`](https://github.com/axel-springer-kugawana/iwb_serenity/tree/b6166032cf8417a47967627ac19847d9724cc753/packages/vue-password#in-modal-boolean) prop (putting a different background);
- it hides the password [when the field becomes empty](https://github.com/axel-springer-kugawana/iwb_serenity/blob/b6166032cf8417a47967627ac19847d9724cc753/packages/vue-password/src/components/Password.vue#L152-L155) (e.g.: when the user deletes all characters);
- [it uses](https://github.com/axel-springer-kugawana/iwb_serenity/blob/b6166032cf8417a47967627ac19847d9724cc753/packages/vue-password/src/components/Password.vue#L124) [`nanoid`](https://github.com/ai/nanoid) instead of `uuid` (better, smaller, faster).

## Aside from the component

Each folder has:
- [x] a [README.md](https://github.com/axel-springer-kugawana/iwb_serenity/blob/b6166032cf8417a47967627ac19847d9724cc753/packages/vue-password/README.md) file with instructions for installation, usage and various stuff (license, development instructions…)
- [x] a [CHANGELOG.md](https://github.com/axel-springer-kugawana/iwb_serenity/blob/b6166032cf8417a47967627ac19847d9724cc753/packages/vue-password/CHANGELOG.md)
- [x] a demo app ([`src/App.vue`](https://github.com/axel-springer-kugawana/iwb_serenity/blob/b6166032cf8417a47967627ac19847d9724cc753/packages/vue-password/src/App.vue)) that can be run with `npm run serve`
- [ ] tests (not done yet)

(Side note: Vue 2 component has a `Password-ts.vue` file in addition to `Password.vue`. It’s useless, but I kept it for history.)

## Next steps

- [ ] Review the PR
- [x] Publish packages
- [ ] Add installation and usage instructions to the [Serenity docs](https://axel-springer-kugawana.github.io/iwb_serenity/).
- [ ] Celebrate
- [ ] Add tests (this one can be done before/after any step)

### CODE REVIEW

**Comment by EmmaPepin** [comment]
@meduzen We can improve a little bit the accessibility by adding : 
- aria-live polite to the span to signify to user the status : password shown|password hidden.
- aria-pressed to the button (true|false, depending the click)

```
<div class="password">
<span class="sr-only" aria-live="polite">Password hidden</span>
<input type="password" autocomplete="current-password" class="input--text" id="ZRh1R9" name="login-password" aria-labelledby="label-ZRh1R9 " aria-invalid="">
<button type="button" class="password__btn button button--transparent button--text" id="show-login-password-ZRh1R9" aria-label="Show password" title="Show password" aria-pressed="false">
<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" fill="currentColor"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm-3-5c0-1.66 1.34-3 3-3s3 1.34 3 3-1.34 3-3 3-3-1.34-3-3z"></path></svg>
</button>
</div>
```

**Comment by meduzen-immoweb** [comment]
Re-reviewable. @EmmaPepin

**Comment by meduzen-immoweb** [comment]
Self-note: import from `iwb-serenity-password-vue-2` may not work in a non-TS project (likely a Webpack loader configuration issue). Workaround awaiting a fix is to import from `/node_modules/iwb-serenity-password-vue-2/src/components/Password.vue`.

**Comment by EmmaPepin** [comment]
@meduzen 
Remark about error management : with the empty data check, it is not possible to check if the field is required.
For example
image
Solution : remove completely the empty check or add another boolean prop, as 'required' or 'emptyAllowed', to make possible the required check.

**Review by EmmaPepin — CHANGES_REQUESTED** [review]
Remark about error management : with the empty data check, it is not possible to check if the field is required.
For example
image
Solution : remove completely the empty check or add another boolean prop, as 'required' or 'emptyAllowed', to make possible the required check.

**Comment by meduzen-immoweb** [comment]
> with the empty data check, it is not possible to check if the field is required. […] Solution : remove completely the empty check or add another boolean prop, as 'required' or 'emptyAllowed', to make possible the required check.

1. The “required” check is currently only done server side, so I propose to remove the `empty` check. If we want to indicate the user that the password is required (which is always the case), then the parent component/form should probably be the one dealing with this.

2. Alternatively, there’s the `required` HTML attribute, but maybe there’s a reason why we don’t use it (accessibility? letting the server be the only “checker” for data?). Do you have any information about that?

3. Another thing: right now it’s possible to initialize a default value for the password (like in the demo app for [the one with an error](https://github.com/axel-springer-kugawana/iwb_serenity/blob/ae637c2a1c1a878cd6b95b825de7172697d2b7e0/packages/vue-password/src/App.vue#L59)), and then the password component initialize its `empty` prop by [checking the value](https://github.com/axel-springer-kugawana/iwb_serenity/blob/ae637c2a1c1a878cd6b95b825de7172697d2b7e0/packages/vue-password/src/components/Password.vue#L131), but it doesn’t make sense to have a default value for a password. So I propose to remove this possibility.

What do you think?

**Comment by EmmaPepin** [comment]
@meduzen-immoweb 
1. 👍 
2. About `required`, i think that a password input will be always required in form (login, change password, user's creation).
I don't see a case where it won't. So, we can add `required` and `aria-required`. If you see a case where it will be, maybe we can use a prop required to manage these attribute as an option.
3. 👍 

Another note, we have to improve the management of the aria-invalid attribute.
For example, in Back Office, when password is saved in browser, this attribute is set to is true, although no error detected.
image

**Comment by meduzen-immoweb** [comment]
I made some updates. There’s rather a lot, so I also published version `v0.3.0` so we can test the changes. If something isn’t suitable, let’s discuss and make choice for a potential 0.4.

- I went for `aria-required` because it pairs well with server validation, and `required` unfortunately causes accessibility issues.
- `aria-invalid` fixed. Can you check it works properly with password autocompletion? On macOS + Chromium, it’s now fine.
- A new `autocomplete` prop.
- Fix input `border-color` when the field has an error and the visibility button is focused, as per discussion with the designer.
- Documentation of accessibility choices.

Everything is normally in the changelog and the docs.

**Comment by meduzen-immoweb** [comment]
I’ve noticed using `v-model="password"` is useless  when the `<form>` is submittable without JavaScript. But the component currently requires it. I think we can safely make it optional.

**Comment by meduzen-immoweb** [comment]
Also: when password is long, doesn’t look nice:

image

**Comment by meduzen-immoweb** [comment]
Merging. 🎉  We will open issue for remaining comments.

**Comment by meduzen-immoweb** [comment]
> Merging. 🎉 We will open issue for remaining comments.

Done: #30 #31.

**Pull request merged**
